# Generated by Django 4.2.4 on 2023-10-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('iban', models.CharField(max_length=30, verbose_name='IBAN')),
                ('bic_swift', models.CharField(max_length=20, verbose_name='BIC/SWIFT')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('twint', models.CharField(max_length=20, verbose_name='TWINT')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
    ]
