# Generated by Django 4.2.4 on 2023-10-26 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
