# Generated by Django 4.2.4 on 2023-10-26 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=4)]),
        ),
    ]
