# Generated by Django 4.2.4 on 2023-10-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0005_alter_customuser_email_alter_customuser_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, default='0000', max_length=4, null=True),
        ),
    ]
