# Generated by Django 4.2.4 on 2023-10-28 13:39

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='category_name', unique=True, verbose_name='Слаг(Автоматичний)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(help_text='Максимум 2200 символів', max_length=2200, verbose_name='Повний опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=models.TextField(help_text='Ви можете вказати колір або розмір ', max_length='999', verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='product_name', unique=True, verbose_name='Слаг(Автоматичний)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_time_create',
            field=models.DateTimeField(auto_now_add=True, help_text='Відображає дату створення товару', verbose_name='Дата створення продукту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_time_update',
            field=models.DateTimeField(auto_now=True, help_text='Відображає дату оновлення товару', verbose_name='Дата оновлення продукту'),
        ),
    ]
