# Generated by Django 4.2.4 on 2023-08-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_detalis',
            new_name='product_details',
        ),
    ]
