# Generated by Django 4.2.4 on 2023-08-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0002_swiper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='image',
            field=models.ImageField(help_text='1400x400', upload_to='images/swiper_images/', verbose_name='Зображення на слайдер'),
        ),
    ]
