# Generated by Django 4.2.4 on 2023-08-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0002_remove_product_product_image54_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_1',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_10',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 10'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_2',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_3',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_4',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_5',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_6',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_7',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image_9',
            field=models.ImageField(blank=True, help_text='Додаткове зображення до товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення 9'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_main_image',
            field=models.ImageField(help_text='Завантажте зображення для товару', upload_to='images/product_main_image/%Y/%m/%d/', verbose_name='Зображення до товару'),
        ),
    ]
