# Generated by Django 4.2.4 on 2023-10-28 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0002_alter_category_category_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_and_orders_App', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='delivery_address',
            field=models.TextField(verbose_name='Адреса доставки'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='delivery_postal_code',
            field=models.CharField(max_length=10, verbose_name='Поштовий індекс'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Електронна пошта'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment_and_orders_App.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Новий'), ('Accepted', 'Прийнятий'), ('Paid', 'Сплачений'), ('Completed', 'Виконаний'), ('In Progress', 'В процесі'), ('Preparing for Shipment', 'Готується до відправлення'), ('Being Delivered', 'Доставляється'), ('Delivered', 'Доставлений'), ('Canceled', 'Скасований')], default='Новий', max_length=225, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна вартість'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна товару'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment_and_orders_App.order', verbose_name='Замовлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogApp.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Кількість'),
        ),
    ]
